"""empty message

Revision ID: 021150e5912c
Revises: 8e3b7865c51a
Create Date: 2023-10-16 19:21:55.159434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '021150e5912c'
down_revision = '8e3b7865c51a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donationInfo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gender', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donationInfo', schema=None) as batch_op:
        batch_op.drop_column('gender')

    # ### end Alembic commands ###
