"""empty message

Revision ID: 649c72824dac
Revises: 68ea16a40f2d
Create Date: 2023-10-05 00:13:48.072691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '649c72824dac'
down_revision = '68ea16a40f2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.alter_column('date',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.alter_column('date',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
