"""empty message

Revision ID: 782cd3d388a9
Revises: a67b1fabd425
Create Date: 2023-10-19 22:33:18.113068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '782cd3d388a9'
down_revision = 'a67b1fabd425'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donationInfo', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Integer(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donationInfo', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(precision=10, scale=2),
               nullable=True)

    # ### end Alembic commands ###
