"""empty message

Revision ID: 8e3b7865c51a
Revises: a71c03098758
Create Date: 2023-10-16 15:45:26.859787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e3b7865c51a'
down_revision = 'a71c03098758'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donationInfo', schema=None) as batch_op:
        batch_op.drop_column('date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donationInfo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.VARCHAR(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
