"""empty message

Revision ID: e13b70222abc
Revises: a7ed132c4c7a
Create Date: 2023-10-14 22:26:49.894546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e13b70222abc'
down_revision = 'a7ed132c4c7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donationInfo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_status', sa.String(length=20), nullable=True))
        batch_op.alter_column('amount',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.Float(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donationInfo', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=sa.Float(),
               type_=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.drop_column('payment_status')

    # ### end Alembic commands ###
